### ISSUE TITLE
[REQ] Support for custom gamedata files

### ISSUE THREAD

**Issue by crashzk** [CS2Plugins/WeaponRestrict#1]
CSSharp itself already supports custom gamedata: https://github.com/roflmuffin/CounterStrikeSharp/pull/194

I believe that a better solution than editing gamedata `/game/csgo/addons/counterstrikesharp/gamedata/gamedata.json` whenever updating CSSharp would be to add the plugin's own gamedata.

**Comment by chycken** [comment]
@Whaliin

**Comment by Whaliin** [comment]
Will look into this

**Comment by Whaliin** [comment]
Updated README.md and added custom WeaponRestrict.json file

**Comment by chycken** [comment]
@Whaliin  thanks dude. I appreciate your work.
Btw a tip:  I think you can also make the json and dll files be in the same place (plugins/weaponrestrict folder), so the plugin loads the json file from the same place where it is.
