### ISSUE TITLE
[REQ] Vip Restrictions

### ISSUE THREAD

**Issue by itsAudioo** [CS2Plugins/WeaponRestrict#11]
Hey brother, 
I was hoping you can add some vip restrictions that will alow us to limit weapon count and weapons to vips, cuz currently they can use all restricted weapons. ofc if this is won't take a lot of your time to develop

**Comment by Whaliin** [comment]
Adding this would complicate the configuration a lot (think vip restrictions for each map plus defaults)
The reason I made this in the first place was to make configuring it really easy so I don't think I will add this
