### ISSUE TITLE
remove awp limiter in awp maps

### ISSUE THREAD

**Issue by mayersgamer** [CS2Plugins/WeaponRestrict#14]
Can you help me remove the limiter in awp_lego_2 map , this is my config : 
-------------------------------------------------------------------------------------------------

// This configuration was automatically generated by CounterStrikeSharp for plugin 'WeaponRestrict', at 2024/08/02 09:47:17
{
  "MessagePrefix": "{Color.Orange}[WeaponRestrict] ",
  "RestrictMessage": "{Color.LightPurple}{0}{Color.Default} is currently restricted to {Color.LightRed}{1}{Color.Default} per team.",
  "DisabledMessage": "{Color.LightPurple}{0}{Color.Default} is currently {Color.LightRed}disabled{Color.Default}.",
  "WeaponQuotas": {
    "weapon_awp": 0.2
  },
  "WeaponLimits": {
    "1": {
      "weapon_awp": 1,
      "weapon_g3sg1": 0,
      "weapon_xm1014": 0,
      "weapon_scar20": 0
    },
    "5": {
      "weapon_awp": 2,
      "weapon_g3sg1": 0,
      "weapon_xm1014": 0,
      "weapon_scar20": 0
    },
    "9": {
      "weapon_awp": 3,
      "weapon_g3sg1": 0,
      "weapon_xm1014": 0,
      "weapon_scar20": 0
    }
  },
  "DoTeamCheck": true,
  "AllowPickup": false,
  "VIPFlag": "@css/vip",
  "MapConfigs": {
    "de_dust2": {
      "WeaponQuotas": {
        "weapon_awp": 0.2
      },
      "WeaponLimits": {
        "weapon_awp": 1
      },
      "awp.*": {}
    }
  },
  "ConfigVersion": 2

-----------------------------------------------------------------------------------
how to prevent admins from getting limited weapons ? 
thank you

**Comment by Whaliin** [comment]
Please look over the [guide](https://github.com/CS2Plugins/WeaponRestrict?tab=readme-ov-file#config) on how to configure the plugin.

**Comment by mayersgamer** [comment]
i already read the guide , and tried diffrent things but its not working , so i ve done something wrong can you give an example using the map awp_lego_2 name
