### ISSUE TITLE
Create PlayerInTeamQuota Mode for Restriction

### ISSUE THREAD

**Issue by umbr1X** [CS2Plugins/WeaponRestrict#7]
"PlayersInTeamQuota": {			// using this method if RestrictMethod = 1. Calculated by players for each team 
		"CT": [					// team
			{
				"4": 0,				// Allowed deagles to CT-team to 0 for 4-7 players
				"8": 4,				// Allowed deagles to CT-team to 4 for 8-15 players
				"16": 7				// Allowed deagles to CT-team to 7 for 16-... players
				// here can add more player conditions using ","
			}
		],
		"T": [					// team
			{
				"4": 3,               // Allowed deagles to T-team to 3 for 4-7 players
				"8": 4,               // Allowed deagles to T-team to 4 for 8-15 players
				"16": 9               // Allowed deagles to T-team to 9 for 16-... players
				// here can add more player conditions using ","
			}
		]
	},

**Comment by Whaliin** [comment]
This exact method of configuring is the primary reason I made this plugin as an alternative. This will not be added.
